baseURL = 'https://alimalik.me/'
languageCode = 'en-us'
title = 'The Digital Frontier'   
theme = 'void'

# Social media lnks
[params]
    [params.social]
    github = "https://github.com/lorax786"
    [params.avatar]
    url = "https://avatar.iran.liara.run/public"

# Main menu
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'My Thoughts'
url = 'https://blog.alimalik.me'
weight = 20

[[menus.main]]
name = 'About Me'
pageRef = '/about'
weight = 401

[caches]
    [caches.images]
    dir = ':cacheDir/images'
